#!/usr/bin/env python3
"""Card de lenguajes y lineas propias, calculada en local.

Un fichero de datos por repositorio; la card se recomputa entera desde todos
ellos. Anadir un repo es idempotente: reprocesarlo sobrescribe su fichero, no
suma dos veces.

    stats.py scan <ruta>     identidades de commit del repo (para authors.txt)
    stats.py add <ruta>      analiza el repo y guarda su fichero de datos
    stats.py list            repos ya analizados
    stats.py build           agrega todo -> stats.json (versionado, anonimo)

Los datos por repo viven fuera de este repositorio (~/.cache/pjg09-stats) para
que los nombres de repos privados no acaben en un repo publico.
"""
import argparse
import fnmatch
import json
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import languages as L  # noqa: E402

DATA_DIR = os.environ.get(
    "PJG09_STATS_DATA", os.path.expanduser("~/.cache/pjg09-stats/repos")
)
# Una linea mas larga que esto delata minificado o datos, no codigo escrito.
MAX_AVG_LINE_LEN = 300
# Marcadores de cabecera de fichero autogenerado (linguist usa heuristicas
# equivalentes). Se buscan solo en las primeras lineas.
GENERATED_MARKERS = (
    "do not edit", "do not modify", "auto-generated", "autogenerated",
    "automatically generated", "generated by", "@generated",
    "this file was generated", "code generated by",
)
GENERATED_SCAN_LINES = 8
BLAME_WORKERS = min(8, (os.cpu_count() or 4))


def git(repo, *args, check=True):
    r = subprocess.run(
        ["git", "-C", repo, *args],
        capture_output=True, text=True, errors="replace",
    )
    if check and r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} fallo en {repo}:\n{r.stderr.strip()}")
    return r.stdout


def load_list(path):
    if not os.path.exists(path):
        return []
    out = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                out.append(line)
    return out


def load_authors():
    a = [x.lower() for x in load_list(os.path.join(HERE, "authors.txt"))]
    if not a:
        sys.exit("scripts/authors.txt vacio: sin identidades no hay nada que contar.")
    return set(a)


def load_excludes():
    return load_list(os.path.join(HERE, "exclude.txt"))


def excluded(rel, patterns):
    return any(fnmatch.fnmatch(rel, p) for p in patterns)


def slug_for(repo):
    origin = git(repo, "config", "--get", "remote.origin.url", check=False).strip()
    if origin:
        s = origin.rstrip("/")
        if s.endswith(".git"):
            s = s[:-4]
        if ":" in s and "://" not in s:          # git@host:owner/repo
            s = s.split(":", 1)[1]
        else:
            s = "/".join(s.split("/")[-2:])
        return s.replace("/", "__")
    return os.path.basename(os.path.abspath(repo))


# --------------------------------------------------------------------------- scan

def cmd_scan(args):
    repo = os.path.abspath(args.path)
    out = git(repo, "log", "--all", "--format=%ae%x09%an")
    seen = {}
    for line in out.splitlines():
        if "\t" not in line:
            continue
        email, name = line.split("\t", 1)
        key = email.lower()
        seen.setdefault(key, [0, set()])
        seen[key][0] += 1
        seen[key][1].add(name)
    known = load_authors()
    print(f"{slug_for(repo)}  ({repo})\n")
    print(f"{'commits':>8}  {'':1} {'email':<45} nombres")
    for email, (n, names) in sorted(seen.items(), key=lambda kv: -kv[1][0]):
        mark = "*" if email in known else " "
        print(f"{n:>8}  {mark} {email:<45} {', '.join(sorted(names))}")
    print("\n* = ya esta en scripts/authors.txt")


# --------------------------------------------------------------------------- add

def blame_file(repo, rel):
    """Devuelve (lineas_por_email, edad_media_por_email, longitud_media_linea)."""
    r = subprocess.run(
        ["git", "-C", repo, "blame", "--line-porcelain", "-w", "-M", "-C",
         "HEAD", "--", rel],
        capture_output=True, text=True, errors="replace",
    )
    if r.returncode != 0:
        return None
    counts, agesum, content_len, nlines = {}, {}, 0, 0
    head_text = []
    email = None
    atime = 0
    for line in r.stdout.split("\n"):
        if line.startswith("author-mail "):
            email = line[12:].strip().strip("<>").lower()
        elif line.startswith("author-time "):
            atime = int(line[12:].strip())
        elif line.startswith("\t"):
            if email is None:
                continue
            counts[email] = counts.get(email, 0) + 1
            agesum[email] = agesum.get(email, 0) + atime
            content_len += len(line) - 1
            nlines += 1
            if nlines <= GENERATED_SCAN_LINES:
                head_text.append(line[1:].lower())
    avg = (content_len / nlines) if nlines else 0
    header = " ".join(head_text)
    generated = any(m in header for m in GENERATED_MARKERS)
    return counts, agesum, avg, generated


def cmd_add(args):
    repo = os.path.abspath(args.path)
    if not os.path.isdir(os.path.join(repo, ".git")):
        sys.exit(f"{repo} no es un repositorio git.")
    authors = load_authors()
    patterns = load_excludes()
    slug = args.slug or slug_for(repo)
    started = time.time()

    head = git(repo, "rev-parse", "HEAD").strip()
    branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip()

    # --- ficheros de HEAD que son codigo reconocido y no estan excluidos
    tracked = [f for f in git(repo, "ls-files", "-z").split("\0") if f]
    candidates = []
    skipped_unknown = {}
    for rel in tracked:
        if not rel or excluded(rel, patterns):
            continue
        lang, color = L.classify(rel)
        if lang is None:
            ext = rel.rsplit("/", 1)[-1]
            ext = ext[ext.rfind("."):] if "." in ext[1:] else ext
            skipped_unknown[ext] = skipped_unknown.get(ext, 0) + 1
            continue
        candidates.append((rel, lang, color))

    print(f"{slug}: {len(candidates)} ficheros de codigo en HEAD "
          f"({len(tracked)} trackeados). Blame en curso...", flush=True)

    langs = {}   # lang -> dict de contadores
    colors = {}
    minified = []
    autogen = []

    def bucket(lang, color):
        colors[lang] = color
        return langs.setdefault(lang, {
            "surviving_lines": 0, "surviving_lines_all_authors": 0,
            "files": 0, "test_lines": 0, "added": 0, "deleted": 0,
            "_agesum": 0,
        })

    def work(item):
        rel, lang, color = item
        res = blame_file(repo, rel)
        return rel, lang, color, res

    with ThreadPoolExecutor(max_workers=BLAME_WORKERS) as pool:
        for rel, lang, color, res in pool.map(work, candidates):
            if res is None:
                continue
            counts, agesum, avg, generated = res
            if avg > MAX_AVG_LINE_LEN:
                minified.append(rel)
                continue
            if generated:
                autogen.append(rel)
                continue
            b = bucket(lang, color)
            mine = sum(n for e, n in counts.items() if e in authors)
            b["surviving_lines_all_authors"] += sum(counts.values())
            if mine:
                b["surviving_lines"] += mine
                b["files"] += 1
                b["_agesum"] += sum(v for e, v in agesum.items() if e in authors)
                if L.is_test(rel):
                    b["test_lines"] += mine

    # --- lineas anadidas/borradas historicamente (metrica A del doc)
    log = git(repo, "log", "HEAD", "--no-merges", "--numstat",
              "--format=%x01%ae", "-z")
    commits_mine = 0
    mine_now = False
    for chunk in log.replace("\0", "\n").split("\x01"):
        if not chunk.strip():
            continue
        lines = chunk.split("\n")
        mine_now = lines[0].strip().lower() in authors
        if mine_now:
            commits_mine += 1
        for entry in lines[1:]:
            parts = entry.split("\t")
            if len(parts) != 3 or not mine_now:
                continue
            a, d, rel = parts
            if a == "-" or excluded(rel, patterns):
                continue
            lang, color = L.classify(rel)
            if lang is None:
                continue
            b = bucket(lang, color)
            b["added"] += int(a)
            b["deleted"] += int(d)

    now = time.time()
    out_langs = {}
    for lang, b in sorted(langs.items()):
        if b["surviving_lines"] == 0 and b["added"] == 0:
            continue
        entry = {k: v for k, v in b.items() if not k.startswith("_")}
        entry["color"] = colors[lang]
        entry["is_code"] = lang not in L.MARKUP_OR_DATA
        if b["surviving_lines"]:
            avg_ts = b["_agesum"] / b["surviving_lines"]
            entry["avg_age_days"] = round((now - avg_ts) / 86400, 1)
        out_langs[lang] = entry

    doc = {
        "slug": slug,
        "path": repo,
        "head": head,
        "branch": branch,
        "private": bool(args.private),
        "analyzed_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "authors": sorted(authors),
        "commits_mine": commits_mine,
        "files_minified_skipped": len(minified),
        "files_generated_skipped": len(autogen),
        "extensions_unrecognized": dict(
            sorted(skipped_unknown.items(), key=lambda kv: -kv[1])[:15]),
        "languages": out_langs,
    }
    os.makedirs(DATA_DIR, exist_ok=True)
    dest = os.path.join(DATA_DIR, slug + ".json")
    with open(dest, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    surv = sum(v["surviving_lines"] for v in out_langs.values())
    add = sum(v["added"] for v in out_langs.values())
    print(f"  {commits_mine} commits tuyos | {surv} lineas vivas | "
          f"{add} anadidas historicas | {time.time()-started:.1f}s")
    if minified or autogen:
        print(f"  descartados: {len(minified)} minificados, "
              f"{len(autogen)} autogenerados")
    for lang, v in sorted(out_langs.items(), key=lambda kv: -kv[1]["surviving_lines"])[:12]:
        if v["surviving_lines"]:
            print(f"    {lang:<22} {v['surviving_lines']:>8} vivas  "
                  f"{v['added']:>8} anadidas")
    if skipped_unknown:
        top = list(doc["extensions_unrecognized"].items())[:6]
        print("  extensiones no reconocidas: " +
              ", ".join(f"{e}({n})" for e, n in top))
    print(f"  -> {dest}")


# --------------------------------------------------------------------------- list

def load_all():
    if not os.path.isdir(DATA_DIR):
        return []
    docs = []
    for name in sorted(os.listdir(DATA_DIR)):
        if name.endswith(".json"):
            with open(os.path.join(DATA_DIR, name), encoding="utf-8") as fh:
                docs.append(json.load(fh))
    return docs


def cmd_list(args):
    docs = load_all()
    if not docs:
        print(f"Ningun repo analizado todavia. Datos en: {DATA_DIR}")
        return
    print(f"{'repo':<38} {'priv':<5} {'vivas':>9} {'anadidas':>10}  analizado")
    for d in docs:
        surv = sum(v["surviving_lines"] for v in d["languages"].values())
        add = sum(v["added"] for v in d["languages"].values())
        print(f"{d['slug']:<38} {'si' if d['private'] else 'no':<5} "
              f"{surv:>9} {add:>10}  {d['analyzed_at'][:10]}")
    print(f"\n{len(docs)} repos en {DATA_DIR}")


# --------------------------------------------------------------------------- build

def cmd_build(args):
    docs = load_all()
    if not docs:
        sys.exit("No hay repos analizados. Usa: stats.py add <ruta>")
    agg = {}
    for d in docs:
        for lang, v in d["languages"].items():
            if lang not in L.ALL_LANGUAGES:
                continue          # quitado del mapa despues de analizar el repo
            b = agg.setdefault(lang, {
                "surviving_lines": 0, "added": 0, "deleted": 0, "files": 0,
                "test_lines": 0, "color": v["color"],
                # recalculado aqui a proposito: si se leyese el `is_code`
                # guardado, cambiar languages.py obligaria a reanalizar todo.
                "is_code": lang not in L.MARKUP_OR_DATA,
                "_agesum": 0.0,
            })
            b["surviving_lines"] += v["surviving_lines"]
            b["added"] += v["added"]
            b["deleted"] += v["deleted"]
            b["files"] += v["files"]
            b["test_lines"] += v["test_lines"]
            b["_agesum"] += v.get("avg_age_days", 0) * v["surviving_lines"]

    code_total = sum(v["surviving_lines"] for v in agg.values() if v["is_code"])
    other_total = sum(v["surviving_lines"] for v in agg.values() if not v["is_code"])

    def entry(lang, v, denom):
        return {
            "name": lang,
            "lines": v["surviving_lines"],
            "percent": round(100 * v["surviving_lines"] / denom, 4) if denom else 0,
            "color": v["color"],
            "files": v["files"],
            "added": v["added"],
            "deleted": v["deleted"],
            "test_lines": v["test_lines"],
            "avg_age_days": round(v["_agesum"] / v["surviving_lines"], 1),
        }

    langs, other = [], []
    for lang, v in agg.items():
        if v["surviving_lines"] == 0:
            continue
        if v["is_code"]:
            langs.append(entry(lang, v, code_total))
        else:
            other.append(entry(lang, v, other_total))
    langs.sort(key=lambda e: -e["lines"])
    other.sort(key=lambda e: -e["lines"])

    tests = sum(e["test_lines"] for e in langs)
    added = sum(e["added"] for e in langs + other)
    deleted = sum(e["deleted"] for e in langs + other)
    out = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "metric": "surviving_lines",
        "metric_desc": "líneas de HEAD atribuidas a Pedro por git blame -w -M -C",
        "repos_analyzed": len(docs),
        "repos_private": sum(1 for d in docs if d["private"]),
        "totals": {
            "lines": code_total,
            "lines_other": other_total,
            "lines_all": code_total + other_total,
            "files": sum(e["files"] for e in langs),
            "added": added,
            "deleted": deleted,
            "commits": sum(d["commits_mine"] for d in docs),
            "delete_ratio": round(deleted / added, 3) if added else 0,
            "test_ratio": round(100 * tests / code_total, 2) if code_total else 0,
        },
        "languages": langs,
        "other": other,
    }
    dest = os.path.join(ROOT, "stats.json")
    with open(dest, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    t = out["totals"]
    print(f"{len(langs)} lenguajes de codigo | {t['lines']} lineas vivas | "
          f"{t['files']} ficheros | {out['repos_analyzed']} repos")
    print(f"tests {t['test_ratio']}% | borrado/anadido {t['delete_ratio']} | "
          f"{t['commits']} commits")
    for e in langs:
        print(f"  {e['name']:<22} {e['percent']:>6.2f}%  {e['lines']:>8}")
    if other:
        print(f"marcado y datos ({t['lines_other']} lineas, fuera del %):")
        for e in other:
            print(f"  {e['name']:<22} {'':>7}  {e['lines']:>8}")
    print(f"-> {dest}")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("scan", help="identidades de commit de un repo")
    s.add_argument("path")
    s.set_defaults(func=cmd_scan)

    s = sub.add_parser("add", help="analizar un repo y guardar sus datos")
    s.add_argument("path")
    s.add_argument("--slug", help="nombre del fichero de datos")
    s.add_argument("--private", action="store_true",
                   help="marcar como repo privado")
    s.set_defaults(func=cmd_add)

    s = sub.add_parser("list", help="repos ya analizados")
    s.set_defaults(func=cmd_list)

    s = sub.add_parser("build", help="agregar todo -> stats.json")
    s.set_defaults(func=cmd_build)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
